\documentclass[final]{beamer}
\usepackage{grffile}
\mode<presentation>{\usetheme{CambridgeUSPOL}}

\usepackage[utf8]{inputenc}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{natbib}
\usepackage{graphicx}
\usepackage{array,booktabs,tabularx}
\newcolumntype{Z}{>{\centering\arraybackslash}X}

% rysunki
\usepackage{tikz}
\usepackage{ifthen}
\usepackage{xxcolor}
\usetikzlibrary{arrows}
\usetikzlibrary[topaths]
\usetikzlibrary{decorations.pathreplacing}
%\usepackage{times}\usefonttheme{professionalfonts}  % times is obsolete
\usefonttheme[onlymath]{serif}
\boldmath
\usepackage[orientation=portrait,size=a0,scale=1.4,debug]{beamerposter}                       % e.g. for DIN-A0 poster
%\usepackage[orientation=portrait,size=a1,scale=1.4,grid,debug]{beamerposter}                  % e.g. for DIN-A1 poster, with optional grid and debug output
%\usepackage[size=custom,width=200,height=120,scale=2,debug]{beamerposter}                     % e.g. for custom size poster
%\usepackage[orientation=portrait,size=a0,scale=1.0,printer=rwth-glossy-uv.df]{beamerposter}   % e.g. for DIN-A0 poster with rwth-glossy-uv printer check
% ...
%

\usecolortheme{seagull}
\useinnertheme{rectangles}
\setbeamercolor{item projected}{bg=darkred}
% \setbeamertemplate{enumerate items}[default]
\setbeamertemplate{navigation symbols}{}
\setbeamercovered{transparent}
\setbeamercolor{block title}{fg=darkred}
\setbeamercolor{local structure}{fg=darkred}

\setbeamercolor*{enumerate item}{fg=darkred}
\setbeamercolor*{enumerate subitem}{fg=darkred}
\setbeamercolor*{enumerate subsubitem}{fg=darkred}

\setbeamercolor*{itemize item}{fg=darkred}
\setbeamercolor*{itemize subitem}{fg=darkred}
\setbeamercolor*{itemize subsubitem}{fg=darkred}

\newlength{\columnheight}
\setlength{\columnheight}{95cm}
\renewcommand{\thetable}{}
\def\andname{,}
\authornote{}

\renewcommand{\APACrefatitle}[2]{}
\renewcommand{\bibliographytypesize}{\footnotesize} 
\renewcommand{\APACrefYearMonthDay}[3]{%
  {\BBOP}{#1}
  {\BBCP}
}

\begin{document}



<<knitrIntro, echo = FALSE, message=FALSE>>=
library(xtable)
library(ggplot2)
library(reshape2)
library(grid)

poster_theme <- theme(plot.background=element_rect(fill = "transparent",
                                                   colour = "transparent"),
                      plot.margin = unit(c(1,1,1,1), "cm"),
                      axis.text.x = element_text(size=17), 
                      axis.text.y = element_text(size=17),
                      axis.title.x = element_text(size=20, vjust = -1), 
                      axis.title.y = element_text(size=20, vjust = 1),
                      strip.text = element_text(size=20),
                      legend.text = element_text(size=17), 
                      legend.title = element_text(size=20),
                      plot.title = element_text(size=28),
                      panel.background = element_rect(fill = "transparent",colour = "black"),
                      legend.direction="horizontal", legend.position = "bottom",
                      legend.background = element_rect(fill="NA"))
@


\date{}
\author{Micha\l{}  Burdukiewicz\inst{1}*, Piotr Sobczyk\inst{2}, Pawe\l{} Mackiewicz\inst{1}, Stefan R\"odiger\inst{3} \\
*michalburdukiewicz@gmail.com}

\institute{\small{\textsuperscript{1}University of Wroc\l{}aw, Department of Genomics

\vspace{0.2cm}

\textsuperscript{2}Wroc\l{}aw University of Technology, Faculty of Pure and Applied Mathematics

\vspace{0.2cm}

\textsuperscript{3}Brandenburg University of Technology Cottbus-Senftenberg, Institute of Biotechnology}

}
\title{\huge dpcR: web server and R package for analysis of digital PCR experiments}

\begin{frame}
  \begin{columns}
    \begin{column}{.46\textwidth}
      \begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}
        \begin{minipage}[T]{.95\textwidth}
          \parbox[t][\columnheight]{\textwidth}
            {
    
        
    \begin{block}{Introduction}
      Secretory signal peptides:
        \begin{itemize}
          \item are short (20-30 residues) N-terminal amino acid sequences,
            \item direct a protein to the endomembrane system and next to the extracellular localization,
            \item possess three distinct domains with variable length and characteristic amino acid composition~\citep{hegde_surprising_2006}.
            \item are universal enough to direct properly proteins in different secretory systems; artifically introduced bacterial signal peptides can guide proteins in mammals~\citep{nagano_2014} and plants~\citep{moeller_2009},
            \item tag among others hormons, immune system proteins, structural proteins, and metabolic enzymes.
        \end{itemize}
    \end{block}
    
    \vfill
    
    \begin{block}{Organization of signal peptide}

      \begin{itemize}
        \item n-region: mostly basic residues~\citep{nielsen_prediction_1998},
        \item h-region: strongly hydrophobic residues~\citep{nielsen_prediction_1998},
        \item c-region: a few polar, uncharged residues~\citep{jain_signal_1994}.
      \end{itemize}
    \end{block}
    \vfill
    
    
    \begin{block}{Hidden semi-Markov model (HSMM) of a signal peptide}
      Assumptions of the model:
      \begin{itemize}
        \item the observable distribution of amino acids arises due to being in a certain region (state),
        \item a duration of the state (the length of given region) is modeled by a probability distribution (other than geometric distribution as in typical hidden Markov models).
      \end{itemize}
    \end{block}
    \vfill
            }
        \end{minipage}
      \end{beamercolorbox}
    \end{column}
    
    
%new column ------------------------------------------------------    
    
    \begin{column}{.54\textwidth}
      \begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}
        \begin{minipage}[T]{.95\textwidth}  
          \parbox[t][\columnheight]{\textwidth}
            {
     
    \begin{block}{Conclusions}
      Hidden semi-Markov models can be used to accurately predict the presence of secretory signal peptides effectively extracting information from very data sets. Prediction of cleavage site position still requires refinement.
    \end{block}
    \vfill 
    
        \begin{block}{Availability and funding}
        \footnotesize{
      signal.hsmm web server: 
      
      \url{www.smorfland.uni.wroc.pl/signalhsmm}
        }
        
        This research was partially funded by KNOW Consortium.
    \end{block}
    \vfill 
     
     
    \begin{block}{Bibliography}
    \tiny{
      \bibliographystyle{apalike}
      \bibliography{amyloids}
    }
    \end{block}
    \vfill
            }
        \end{minipage}
      \end{beamercolorbox}
    \end{column}
  \end{columns}  
\end{frame}
\end{document}